### ISSUE TITLE
add certain auto tags 

### ISSUE THREAD

**Issue by dabezt31** [DiscordGIR/gir#12]
name explains itself, basically, when a user asks or says something, the bot will automatically say something. Some examples may include:
1. Bot does “!t blobs” when a user asks how to save blobs 
2. Bot does “!t blobsfaq” when a user asks what blobs are
3. (I don’t think there’s a tag for this already) bot says jb status, basically, all A11- devices can be jailbroken on any version, however for A12+ its limited to 14.3 and below
4. Bot does “!t bypass” when someone asks “is there a bypass for” 
5. Bot does “!t Altstore” when a user asks “how do I sideload” 

There are many more examples, but those are just a few

**Comment by SlimShadyIAm** [comment]
Solid ideas. How can we ensure there aren't false positives? That's my main reservation with this.

**Comment by dabezt31** [comment]
Great question, while I do think false positives would be a con that’s sometimes unavailable, can’t you add a list that the bot doesn’t detect? Like if someone had said “how to bypass WiFi checks in setup” it wouldn’t detect it as iCloud, the only way, for me it seems, to see what would be on the list is to deploy and test feature, people will definitely tell what to add to the list of things not to detect. Sincerely, below average
