### ISSUE TITLE
[Bug] It is possible to bypass word filters without triggering GIR

### ISSUE THREAD

**Issue by CoocooFroggy** [DiscordGIR/gir#19]
Word added
<img width="597" alt="etawen Added" src="https://user-images.githubusercontent.com/45371102/128070117-09d84e8e-5272-4d35-9625-26f754c04db8.png">
Proof of filter
<img width="607" alt="etawen Triggered" src="https://user-images.githubusercontent.com/45371102/128070119-b4d08e92-e12a-4b33-93f9-066863bdd36a.png">
Bypass
<img width="606" alt="etawen Bypassed" src="https://user-images.githubusercontent.com/45371102/128070135-e311c942-01e0-4cd7-b1d0-d8865e816730.png">

**Comment by proprdev** [comment]
??
